#include <stdlib.h>
#include <string.h>
#include <vector>
#include <string>
#include <iostream>

#define STIM_CLI_RETURN_SUCCESS     0
#define STIM_CLI_RETURN_USAGE_ERROR 1
#define STIM_CLI_RETURN_NO_RESULTS  2

#define STIM_ENV_HOME "STIM_HOME"
#define STIM_ENV_CONTRACT "STIM_CONTRACT"

#define STIM_ENV_FAKENOW "STIM_FAKE_TIME"

#define STIM_ENV_REPORT_FORMAT "STIM_REPORT_FORMAT"
#define STIM_ENV_TIMESTAMP_FORMAT "STIM_TIMESTAMP_FORMAT"
#define STIM_ENV_LOG_FORMAT "STIM_REPORT_FORMAT_LOG"

#define STIM_DEFAULT_HOME ".stim"
#define STIM_DEFAULT_CONTRACT "general"

#define STIM_DEFAULT_REPORT_FORMAT "%BEGIN% - %END% | %ELAPSED% | %DETAIL%\n%LOG%"
#define STIM_DEFAULT_LOG_FORMAT "  %WHEN% %LOG%\n"
#define STIM_DEFAULT_TIMESTAMP_FORMAT "%Y%m%d %H:%M:%S"
